### ISSUE TITLE
link routing

### ISSUE THREAD

**Issue by Chrila2509** [htl-perg-2018-19-4ahif/angular-routing-example-Chrila2509#1]
https://adoring-davinci-28395b.netlify.com

**Comment by rstropek** [comment]
Hi @Chrila2509!

Well done 👍, the extra point is yours.

You could improve your app a little bit. Currently, you are just hiding the description of the Pokemon (because of `[hidden]` on `a`). You could remove the entire `<li>`. That would look even nicer. However, that's just a minor issue.

Greetings,
Rainer Stropek.
